### ISSUE TITLE
Publish action fails

### ISSUE THREAD

**Issue by mdbenito** [aai-institute/pyDVL#418]
The check for a tag to be on the master branch [seems to be at fault](https://github.com/aai-institute/pyDVL/actions/runs/6059344584). That action ran before the main pipeline running on master was finished. (??)

**Comment by mdbenito** [comment]
@AnesBenmerzoug Any ideas? I ran the release script, then created the github release. I would expect the publish action to fail because the default pipeline hasn't run yet and the docs are not ready or whatever (we should probably add to the docs that one needs to wait). But the failure is about not being in the right branch, which is confusing.

**Comment by AnesBenmerzoug** [comment]
Sorry, it's my mistake. This operator in [this condition](https://github.com/aai-institute/pyDVL/blob/develop/.github/workflows/publish.yaml#L51) should have been on OR instead of an AND. I will simplify and fix that pipeline in a new PR (hopefully this well be the last time). For now we can manually trigger the workflow in order to publish the docs and package.

**Comment by mdbenito** [comment]
>  For now we can manually trigger the workflow in order to publish the docs and package.

I'm afraid [that doesn't work either](https://github.com/aai-institute/pyDVL/actions/runs/6059490165). The docs fail for some obscure reason. 

> As for the publish pipeline running before the main pipeline. I think there is no simple solution for that. We could trigger it the publish pipeline from the main pipeline, but I think that we need to set something up first before being able to use that.

It's fine to have to wait, we just need to document it
