### ISSUE TITLE
Include mypy in pre-commit

### ISSUE THREAD

**Issue by jakobkruse1** [aai-institute/pyDVL#530]
I think not running mypy in pre-commit, but running it in the CI is a bit annoying.
You write code, pre-commit passes, then the CI Lint job fails.
I would suggest to add mypy to pre-commit. 
While we are at it, we may also consider using a proper linter like ruff for speedup and convenience as well as other checks if wanted.

**Comment by AnesBenmerzoug** [comment]
I think this is a bad idea.

mypy is slow. Even if it isn't at first, it quickly becomes slow and slows down the development because for every commit you would have to wait while it does its thing. If you follow best practices and commit often then you quickly imagine how frustrating this becomes.

As for ruff, I think it would be nice if we configure it properly and don't enable everything. I still prefer black's formatting and isort's import sorting but perhaps ruff can be made to work like them with the right configuration.

I suggest we reject the mypy suggestion.

**Comment by mdbenito** [comment]
> About @mdbenito 's comment: I absolutely hate pre-push (very much my personal preference). By using it, I notice errors way too late, when the commit has already happened. Therefore, I still need to add `git commit -m "fix linter"` which could have been avoided by using pre-commit. However, the way how a user installs their pre-commit is their own decision. We may add to the CONTRIBUTING.md that `pre-commit install` and `pre-commit install --hook-type pre-push` are both valid options of using pre-commit in pyDVL.

Why not `git commit --amend` ?

**Comment by mdbenito** [comment]
To summarize:
* Yes to ruff, eventually, but no priority
* Leave the hook for mypy to the discretion of the dev

So I vote to close this in favour of another issue for ruff
